const repotemplate = [
    {
        templatename: "[Frontend] React TS Tailwind Radix Jan2026",
        templatepath: "reactapp",
        type:         "frontend",
        installcmd:   "npm install",
        startcmd:     "npm run dev",
        stopcmd:      "npm run stop",
        buildcmd:     "npm run build",
        lintcmd:      "npm run lint",
        testcmd:      "",
        devurl:       "http://localhost:3000",
        icon:         "fa-brands fa-react",
    },
    {
        templatename: "[Backend] Node TS Nodemon Jan2026",
        templatepath: "nodemon",
        type:         "backend",
        installcmd:   "npm install",
        startcmd:     "npm run dev",
        stopcmd:      "npm run stop",
        buildcmd:     "npm run build",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:8000",
        icon:         "fa-brands fa-node-js",
    },
    {
        templatename: "[Backend] PHP Docker",
        templatepath: "php_docker",
        type:         "backend",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:8000",
        icon:         "fa-brands fa-php",
    },
    {
        templatename: "[Database] Supabase Jan2026",
        templatepath: "supabase",
        type:         "database",
        installcmd:   "npm install",
        startcmd:     "npm run start",
        stopcmd:      "npm run stop",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:54321",
        icon:         "fas fa-database",
    },
    {
        templatename: "[Service] Localstack Jan2026",
        templatepath: "aws",
        type:         "service",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "",
        icon:         "fa-brands fa-aws",
    },
    {
        templatename: "[Service] Redis Jan2026",
        templatepath: "redis",
        type:         "service",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "",
        icon:         "fas fa-database",
    }
];

module.exports = repotemplate;