const repotemplate = [
    {
        templatename: "[Frontend] React TS Tailwind Radix",
        templatepath: "reactapp",
        type:         "frontend",
        installcmd:   "npm install",
        devcmd:       "vite",
        startcmd:     "",
        stopcmd:      "npx -y kill-port 3000",
        buildcmd:     "tsc -b && vite build",
        lintcmd:      "eslint .",
        testcmd:      "",
        devurl:       "http://localhost:3000",
        icon:         "fa-brands fa-react",
    },
    {
        templatename: "[Backend] Node TS Nodemon",
        templatepath: "nodemon",
        type:         "backend",
        installcmd:   "npm install",
        startcmd:     "node dist/index.js",
        devcmd:       "ts-node src/index.ts",
        stopcmd:      "npx -y kill-port 8080",
        buildcmd:     "tsc",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:8080",
        icon:         "fa-brands fa-node-js",
    },
    {
        templatename: "[Backend] Node TS Socket",
        templatepath: "node_socket_ts",
        type:         "backend",
        installcmd:   "npm install",
        startcmd:     "node dist/index.js",
        devcmd:       "nodemon",
        stopcmd:      "npx -y kill-port 8081",
        buildcmd:     "tsc",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:8081",
        icon:         "fa-brands fa-node-js",
    },
    {
        templatename: "[Backend] PHP Docker",
        templatepath: "php_docker",
        type:         "backend",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        devcmd:       "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:8000",
        icon:         "fa-brands fa-php",
    },
    {
        templatename: "[Database] Supabase",
        templatepath: "supabase",
        type:         "database",
        installcmd:   "npm install",
        startcmd:     "supabase start",
        devcmd:       "supabase start",
        stopcmd:      "supabase stop",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "http://localhost:54321",
        icon:         "fas fa-database",
    },
    {
        templatename: "[Service] Localstack",
        templatepath: "aws",
        type:         "service",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        devcmd:       "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "",
        icon:         "fa-brands fa-aws",
    },
    {
        templatename: "[Service] Redis",
        templatepath: "redis",
        type:         "service",
        installcmd:   "",
        startcmd:     "docker compose up -d",
        devcmd:       "docker compose up -d",
        stopcmd:      "docker compose down",
        buildcmd:     "",
        lintcmd:      "",
        testcmd:      "",
        devurl:       "",
        icon:         "fas fa-database",
    }
];

module.exports = repotemplate;